---
title: "Inschrijvingen MSI S1 Y2020/21"
output: html_notebook
---



```{r include=FALSE}
library(leaflet)
library(tidyverse)
library(knitr)
library(plotly)
library(htmltools)

# locale("nl")
newDF <- read.csv("inschrijvingen.csv",na.strings = c("", "NA")) %>% na.omit() %>% mutate(Lat = jitter(Lat, factor = 1.5), Lon = jitter(Lon, factor = 1.5))
n <- dim(newDF)[1]
newDF$Label <- sapply(1:n, function(x) HTML(paste("<b>",newDF[x,4], "</b>", "<br>", newDF[x,2])))

tblGeslacht <- table(newDF$Geslacht, newDF$OpleidingType) %>% addmargins(., FUN = list(Totaal = sum), quiet = TRUE)
tblOpleidingType <- table(newDF$Instelling, newDF$OpleidingType) %>% addmargins(., FUN = list(Totaal = sum), quiet = TRUE)

tblOpleidingNaam <- table(newDF$Instelling, newDF$OpleidingNaam) %>% addmargins(., FUN = list(Totaal = sum), quiet = TRUE)

cntHAN <- filter(newDF, Plaats == "Arnhem") %>% dim
```

<hr>
In totaal hebben zich **`r n`** deelnemers aangemeld.
<hr>

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
kable(tblGeslacht, format = "pandoc", caption = "Tab.1 - Verdeling geslacht en opleidingtype", padding = 2)
```
<hr>
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
kable(tblOpleidingType, format = "pandoc", caption = "Tab.2 - Verdeling instelling en opleidingtype", padding = 2)
```
<hr>

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
pal <- colorFactor(c("#FD0E35", "#FDFF00", "#6CDAE7"), domain = c("ECON", "ICT", "ENGR"))

leaflet(newDF, width = 900) %>%
  addTiles() %>%
  addCircleMarkers(radius = 12, color = ~pal(OpleidingType), opacity = 0.8, popup = ~Label)
```
<hr>

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
dfGeslacht <- data.frame(title = 'Verdeling inschrijvingen naar geslacht', Geslacht = rownames(tblGeslacht)[1:2], Aantal = tblGeslacht[1:2])
plot_ly(dfGeslacht, labels = ~Geslacht, values = ~Aantal, type = 'pie', width = 700) %>% layout(showlegend = TRUE) %>% layout(title = 'Verdeling inschrijvingen naar geslacht')
```
<hr>

```{r echo=FALSE, warning=FALSE}
dfOpleidingType <- data.frame(Type = colnames(tblOpleidingType)[1:3], Aantal = tblOpleidingType[dim(tblOpleidingType)[1],1:3])
plot_ly(dfOpleidingType, labels = ~Type, values = ~Aantal, type = 'pie', width = 700) %>% layout(showlegend = TRUE) %>% layout(title = 'Verdeling inschrijvingen naar opleidingstype')
```

```{r echo=FALSE, warning=FALSE}
dfOpleidingNaam <- data.frame(Naam = colnames(tblOpleidingNaam)[1:11], Aantal = tblOpleidingNaam[dim(tblOpleidingNaam)[1],1:11])
plot_ly(dfOpleidingNaam, labels = ~Naam, values = ~Aantal, type = 'pie', width = 700) %>% layout(showlegend = TRUE) %>% layout(title = 'Verdeling inschrijvingen naar opleiding')
```




```{r echo=FALSE, warning=FALSE}
dfInstelling <- data.frame(Instelling = rownames(tblOpleiding)[1:3], Aantal = tblOpleiding[1:3,dim(tblOpleiding)[2]])
plot_ly(dfInstelling, labels = ~Instelling, values = ~Aantal, type = 'pie', width = 700) %>% layout(showlegend = TRUE) %>% layout(title = 'Verdeling inschrijvingen naar instelling')
```